### ISSUE TITLE
OWIN version

### ISSUE THREAD

**Issue by mderriey** [uglybugger/NotDeadYet#5]
Hi,

Would you be interested in having an OWIN version of NotDeadYet?
@robdmoore told me about this project and we could have a use case for an OWIN-only version, even though using to Web API is OK.

I started working on it and, I can issue a PR if you're interested, and we can talk about it.

Cheers!

**Comment by uglybugger** [comment]
Finally catching up on random bits of OSS work. If you have a fork in a usable state, I'd be happy to chat. No stress if not :)
